format = """
$username\
$os\
$directory\
$git_branch\
$git_status
$character
"""

[git_branch]
disabled = false
format = "[   < $symbol $branch]()"

[git_status]
disabled = false
format = "[$all_status$ahead_behind >]()"

[directory]
style = "#FFFFFF"
format = "[  < $path >]($style)"

[username]
disabled = false
show_always = true
style_user = "#FFFFFF"
style_root = "#FFFFFF"
format = "[< $user]($style)"

[os]
disabled = false
style = "#FFFFFF"

[os.symbols]
Arch = " ArchLinux > "
Debian = " Debian > "
Ubuntu = " Ubuntu > "
Artix = " Artix > "
NixOS = " NixOS > "
FreeBSD = " FreeBSD > "
EndeavourOS = " EndeavourOS > "
SUSE = " OpenSUSE > "
Macos = " MacOS > "
Windows = " Windows > "
Mint = " LinuxMint > "
Fedora = " Fedora > "
Gentoo = " Gentoo > "
Manjaro = " Manjaro > "
Alpine = " Alpine > "
Pop = " PopOS > "
CentOS = " CentOS > "
Redhat = " RedHat > "
RedHatEnterprise = " RedHat > "
OpenBSD = " OpenBSD > "
Void = " VoidLinux > "
MidnightBSD = " MidnightBSD > "
Android = " Android > "
Kali = " KaliLinux > "
Garuda = " Garuda > "
Raspbian = " Raspbian > "
HardenedBSD = " HardendBSD > "

[character]
success_symbol = "[>](fg:#FFFFFF)"
error_symbol = "[>](fg:#FF0000)"
vimcmd_symbol = "[>](fg:#00FF00)"
